In [1]:
# Day-06 Data Cleaning Task

In [2]:
# Import Pandas Library 

import pandas as pd

In [3]:
# Load the Dataset (Superstore)

df = pd.read_csv("Sample - Superstore.csv", encoding="Latin1")

In [ ]:
# Filter Rows (sales greater than 10000)

filter_sales = df[df["Sales"]>10000]
filter_sales

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2623,2624,CA-2017-127180,10/22/2017,10/24/2017,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,10024,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888
2697,2698,CA-2014-145317,3/18/2014,3/23/2014,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,32216,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784
4190,4191,CA-2017-166709,11/17/2017,11/22/2017,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856
6826,6827,CA-2016-118689,10/2/2016,10/9/2016,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760
8153,8154,CA-2017-140151,3/23/2017,3/25/2017,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808

In [12]:
# Filter profit rows greater than 6000

profit_rows = df[df["Profit"]>6000]
profit_rows

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
6826,6827,CA-2016-118689,10/2/2016,10/9/2016,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.95,5,0.0,8399.9760
8153,8154,CA-2017-140151,3/23/2017,3/25/2017,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.96,4,0.0,6719.9808

In [15]:
# Filter rows where Quantity greaer than 13

quantity_rows = df[df["Quantity"]>13]
quantity_rows

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
113,114,CA-2014-115259,8/25/2014,8/27/2014,Second Class,RC-19960,Ryan Crowe,Consumer,United States,Columbus,...,43229,East,OFF-FA-10000621,Office Supplies,Fasteners,"OIC Colored Binder Clips, Assorted Sizes",40.096,14,0.2,14.5348
139,140,CA-2016-145583,10/13/2016,10/19/2016,Standard Class,LC-16885,Lena Creighton,Consumer,United States,Roseville,...,95661,West,FUR-FU-10001706,Furniture,Furnishings,Longer-Life Soft White Bulbs,43.120,14,0.0,20.6976
575,576,CA-2015-149713,9/18/2015,9/22/2015,Second Class,TG-21640,Trudy Glocke,Consumer,United States,Long Beach,...,90805,West,OFF-PA-10004530,Office Supplies,Paper,Personal Creations Ink Jet Cards and Labels,160.720,14,0.0,78.7528
660,661,CA-2015-146563,8/24/2015,8/28/2015,Standard Class,CB-12025,Cassandra Brandow,Consumer,United States,Arlington,...,76017,Central,OFF-ST-10001511,Office Supplies,Storage,Space Solutions Commercial Steel Shelving,724.080,14,0.2,-135.7650
1045,1046,CA-2017-152702,10/12/2017,10/16/2017,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Rockford,...,61107,Central,FUR-CH-10002304,Furniture,Chairs,"Global Stack Chair without Arms, Black",254.604,14,0.3,-18.1860
1363,1364,US-2017-155425,11/10/2017,11/11/2017,First Class,AB-10600,Ann Blume,Corporate,United States,Tucson,...,85705,West,OFF-BI-10001036,Office Supplies,Binders,Cardinal EasyOpen D-Ring Binders,38.388,14,0.7,-25.5920
1429,1430,US-2015-164448,10/31/2015,11/4/2015,Second Class,DK-12835,Damala Kotsonis,Corporate,United States,Salinas,...,93905,West,OFF-LA-10003510,Office Supplies,Labels,Avery 4027 File Folder Labels for Dot Matrix P...,427.420,14,0.0,196.6132
1433,1434,CA-2014-120768,12/19/2014,12/21/2014,Second Class,IM-15070,Irene Maddox,Consumer,United States,Florence,...,35630,South,FUR-CH-10000513,Furniture,Chairs,High-Back Leather Manager's Chair,1819.860,14,0.0,163.7874
1711,1712,CA-2017-123491,10/30/2017,11/5/2017,Standard Class,JK-15205,Jamie Kunitz,Consumer,United States,San Francisco,...,94122,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",1702.120,14,0.0,510.6360
2793,2794,CA-2014-154599,4/12/2014,4/17/2014,Standard Class,KN-16450,Kean Nguyen,Corporate,United States,Redondo Beach,...,90278,West,TEC-PH-10001557,Technology,Phones,Pyle PMP37LED,1075.088,14,0.2,94.0702
2947,2948,CA-2017-169859,12/14/2017,12/18/2017,Standard Class,MP-18175,Mike Pelletier,Home Office,United States,San Diego,...,92024,West,OFF-BI-10000174,Office Supplies,Binders,Wilson Jones Clip & Carry Folder Binder Tool f...,64.960,14,0.2,22.7360
3441,3442,CA-2014-158337,3/11/2014,3/14/2014,Second Class,KA-16525,Kelly Andreada,Consumer,United States,New York City,...,10024,East,OFF-PA-10002137,Office Supplies,Paper,"Southworth 100% Résumé Paper, 24lb.",108.920,14,0.0,49.0140
3902,3903,US-2015-119312,10/2/2015,10/7/2015,Second Class,CS-12400,Christopher Schild,Home Office,United States,Los Angeles,...,90045,West,OFF-ST-10000943,Office Supplies,Storage,Eldon ProFile File 'N Store Portable File Tub ...,270.340,14,0.0,75.6952
5385,5386,CA-2017-161410,6/26/2017,7/3/2017,Standard Class,CC-12220,Chris Cortes,Consumer,United States,Philadelphia,...,19143,East,TEC-PH-10000673,Technology,Phones,Plantronics Voyager Pro HD - Bluetooth Headset,545.916,14,0.4,72.7888
5646,5647,CA-2015-104241,1/4/2015,1/9/2015,Standard Class,AG-10495,Andrew Gjertsen,Corporate,United States,Alexandria,...,22304,South,FUR-FU-10001473,Furniture,Furnishings,DAX Wood Document Frame,192.220,14,0.0,69.1992
5668,5669,CA-2016-142405,6/11/2016,6/15/2016,Standard Class,SE-20110,Sanjit Engle,Consumer,United States,Seattle,...,98103,West,OFF-BI-10004728,Office Supplies,Binders,Wilson Jones Turn Tabs Binder Tool for Ring Bi...,53.984,14,0.2,17.5448
6131,6132,CA-2014-163447,12/27/2014,12/31/2014,Standard Class,TB-21190,Thomas Brumley,Home Office,United States,New York City,...,10011,East,FUR-CH-10004477,Furniture,Chairs,"Global Push Button Manager's Chair, Indigo",767.214,14,0.1,161.9674
6488,6489,CA-2015-120621,3/21/2015,3/26/2015,Standard Class,JW-16075,Julia West,Consumer,United States,Jacksonville,...,28540,South,OFF-PA-10002254,Office Supplies,Paper,Xerox 1883,295.456,14,0.2,96.0232
6499,6500,CA-2015-103135,7/24/2015,7/28/2015,Standard Class,SS-20515,Shirley Schmidt,Home Office,United States,Louisville,...,40214,South,TEC-AC-10003289,Technology,Accessories,Anker Ultra-Slim Mini Bluetooth 3.0 Wireless K...,279.860,14,0.0,64.3678
6628,6629,CA-2015-135489,9/19/2015,9/22/2015,Second Class,GW-14605,Giulietta Weimer,Consumer,United States,New York City,...,10024,East,TEC-PH-10000011,Technology,Phones,PureGear Roll-On Screen Protector,279.860,14,0.0,134.3328
7387,7388,CA-2016-105732,9/13/2016,9/18/2016,Standard Class,AG-10270,Alejandro Grove,Consumer,United States,Omaha,...,68104,Central,FUR-FU-10003664,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",1336.440,14,0.0,387.5676
8074,8075,CA-2017-151750,1/1/2017,1/5/2017,Standard Class,JM-15250,Janet Martin,Consumer,United States,Huntsville,...,77340,Central,OFF-BI-10000343,Office Supplies,Binders,"Pressboard Covers with Storage Hooks, 9 1/2"" x...",13.748,14,0.8,-22.6842
8521,8522,CA-2016-141887,1/11/2016,1/15/2016,Standard Class,MP-17470,Mark Packer,Home Office,United States,Columbus,...,43229,East,FUR-FU-10002268,Furniture,Furnishings,Ultra Door Push Plate,54.992,14,0.2,8.9362
8935,8936,CA-2017-130036,8/27/2017,8/27/2017,Same Day,BP-11185,Ben Peterman,Corporate,United States,Philadelphia,...,19120,East,TEC-AC-10001908,Technology,Accessories,Logitech Wireless Headset h800,1119.888,14,0.2,209.9790
9168,9169,CA-2016-140571,3/15/2016,3/19/2016,Standard Class,SJ-20125,Sanjit Jacobs,Home Office,United States,Jackson,...,39212,South,OFF-PA-10001954,Office Supplies,Paper,Xerox 1964,319.760,14,0.0,147.0896
9515,9516,CA-2014-154165,2/17/2014,2/24/2014,Standard Class,DL-13315,Delfina Latchford,Consumer,United States,Chicago,...,60653,Central,OFF-AR-10003631,Office Supplies,Art,Staples in misc. colors,54.208,14,0.2,8.8088
9532,9533,CA-2016-116596,10/27/2016,10/31/2016,Standard Class,BW-11200,Ben Wallace,Consumer,United States,New York City,...,10011,East,FUR-CH-10000553,Furniture,Chairs,"Metal Folding Chairs, Beige, 4/Carton",427.644,14,0.1,80.7772
9941,9942,CA-2017-164028,11/24/2017,11/30/2017,Standard Class,JL-15835,John Lee,Consumer,United States,San Francisco,...,94122,West,TEC-AC-10001772,Technology,Accessories,Memorex Mini Travel Drive 16 GB USB 2.0 Flash ...,223.580,14,0.0,87.1962
9979,9980,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-BI-10002026,Office Supplies,Binders,Ibico Recycled Linen-Style Covers,437.472,14,0.2,153.1152

In [16]:
# Where Ship mode is second class

ship_mode = df[df["Ship Mode"]=="Second Class"]
ship_mode

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.940,3,0.0,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
17,18,CA-2014-167164,5/13/2014,5/15/2014,Second Class,AG-10270,Alejandro Grove,Consumer,United States,West Jordan,...,84084,West,OFF-ST-10000107,Office Supplies,Storage,Fellowes Super Stor/Drawer,55.500,2,0.0,9.9900
18,19,CA-2014-143336,8/27/2014,9/1/2014,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,...,94109,West,OFF-AR-10003056,Office Supplies,Art,Newell 341,8.560,2,0.0,2.4824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9965,9966,CA-2016-146374,12/5/2016,12/10/2016,Second Class,HE-14800,Harold Engle,Corporate,United States,Newark,...,19711,East,OFF-PA-10000349,Office Supplies,Paper,Easy-staple paper,4.980,1,0.0,2.3406
9966,9967,CA-2016-146374,12/5/2016,12/10/2016,Second Class,HE-14800,Harold Engle,Corporate,United States,Newark,...,19711,East,OFF-EN-10004483,Office Supplies,Envelopes,"#10 White Business Envelopes,4 1/8 x 9 1/2",109.690,7,0.0,51.5543
9980,9981,US-2015-151435,9/6/2015,9/9/2015,Second Class,SW-20455,Shaun Weien,Consumer,United States,Lafayette,...,70506,South,FUR-TA-10001039,Furniture,Tables,KI Adjustable-Height Table,85.980,1,0.0,22.3548
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [18]:
# where region is west and sales are greater than 5000

west_sales = df[(df["Region"]=="West") & (df["Sales"] > 5000)]
west_sales

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2505,2506,CA-2014-143917,7/25/2014,7/27/2014,Second Class,KL-16645,Ken Lonsdale,Consumer,United States,San Francisco,...,94122,West,OFF-SU-10000151,Office Supplies,Supplies,High Speed Automatic Electric Letter Opener,8187.65,5,0.0,327.5060
8153,8154,CA-2017-140151,3/23/2017,3/25/2017,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.96,4,0.0,6719.9808
8858,8859,CA-2017-135909,10/13/2017,10/20/2017,Standard Class,JW-15220,Jane Waco,Corporate,United States,Sacramento,...,95823,West,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,5083.96,5,0.2,1906.4850

In [19]:
# Select the Columns 

df["Sales"]

0       261.9600
1       731.9400
2        14.6200
3       957.5775
4        22.3680
          ...
9989     25.2480
9990     91.9600
9991    258.5760
9992     29.6000
9993    243.1600
Name: Sales, Length: 9994, dtype: float64

In [21]:
df[["Customer Name", "Sales", "Profit"]]

         Customer Name     Sales    Profit
0          Claire Gute  261.9600   41.9136
1          Claire Gute  731.9400  219.5820
2      Darrin Van Huff   14.6200    6.8714
3       Sean O'Donnell  957.5775 -383.0310
4       Sean O'Donnell   22.3680    2.5164
...                ...       ...       ...
9989  Tom Boeckenhauer   25.2480    4.1028
9990       Dave Brooks   91.9600   15.6332
9991       Dave Brooks  258.5760   19.3932
9992       Dave Brooks   29.6000   13.3200
9993      Chris Cortes  243.1600   72.9480

[9994 rows x 3 columns]

In [22]:
# Select the OrderID and Region

df[["Order ID","Region"]]

            Order ID Region
0     CA-2016-152156  South
1     CA-2016-152156  South
2     CA-2016-138688   West
3     US-2015-108966  South
4     US-2015-108966  South
...              ...    ...
9989  CA-2014-110422  South
9990  CA-2017-121258   West
9991  CA-2017-121258   West
9992  CA-2017-121258   West
9993  CA-2017-119914   West

[9994 rows x 2 columns]

In [23]:
# Sort Values

df.sort_values("Sales", ascending=True)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
4101,4102,US-2017-102288,6/19/2017,6/23/2017,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,United States,Houston,...,77095,Central,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100
9292,9293,CA-2017-124114,3/2/2017,3/2/2017,Same Day,RS-19765,Roland Schwarz,Corporate,United States,Waco,...,76706,Central,OFF-BI-10004022,Office Supplies,Binders,Acco Suede Grain Vinyl Round Ring Binder,0.556,1,0.8,-0.9452
8658,8659,CA-2016-168361,6/21/2016,6/25/2016,Standard Class,KB-16600,Ken Brennan,Corporate,United States,Chicago,...,60623,Central,OFF-BI-10003727,Office Supplies,Binders,Avery Durable Slant Ring Binders With Label Ho...,0.836,1,0.8,-1.3376
4711,4712,CA-2014-112403,3/31/2014,3/31/2014,Same Day,JO-15280,Jas O'Carroll,Consumer,United States,Philadelphia,...,19120,East,OFF-BI-10003529,Office Supplies,Binders,Avery Round Ring Poly Binders,0.852,1,0.7,-0.5964
2106,2107,US-2014-152723,9/26/2014,9/26/2014,Same Day,HG-14965,Henry Goldwyn,Corporate,United States,Mesquite,...,75150,Central,OFF-BI-10003460,Office Supplies,Binders,Acco 3-Hole Punch,0.876,1,0.8,-1.4016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4190,4191,CA-2017-166709,11/17/2017,11/22/2017,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856
2623,2624,CA-2017-127180,10/22/2017,10/24/2017,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,10024,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888
8153,8154,CA-2017-140151,3/23/2017,3/25/2017,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808
6826,6827,CA-2016-118689,10/2/2016,10/9/2016,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760
2697,2698,CA-2014-145317,3/18/2014,3/23/2014,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,32216,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784

In [24]:
df.sort_values("Profit", ascending=False)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
6826,6827,CA-2016-118689,10/2/2016,10/9/2016,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760
8153,8154,CA-2017-140151,3/23/2017,3/25/2017,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808
4190,4191,CA-2017-166709,11/17/2017,11/22/2017,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856
9039,9040,CA-2016-117121,12/17/2016,12/21/2016,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Detroit,...,48205,Central,OFF-BI-10000545,Office Supplies,Binders,GBC Ibimaster 500 Manual ProClick Binding System,9892.740,13,0.0,4946.3700
4098,4099,CA-2014-116904,9/23/2014,9/28/2014,Standard Class,SC-20095,Sanjit Chand,Consumer,United States,Minneapolis,...,55407,Central,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,9449.950,5,0.0,4630.4755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4991,4992,US-2017-122714,12/7/2017,12/13/2017,Standard Class,HG-14965,Henry Goldwyn,Corporate,United States,Chicago,...,60653,Central,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,1889.990,5,0.8,-2929.4845
3011,3012,CA-2017-134845,4/17/2017,4/23/2017,Standard Class,SR-20425,Sharelle Roach,Home Office,United States,Louisville,...,80027,West,TEC-MA-10000822,Technology,Machines,Lexmark MX611dhe Monochrome Laser Printer,2549.985,5,0.7,-3399.9800
9774,9775,CA-2014-169019,7/26/2014,7/30/2014,Standard Class,LF-17185,Luke Foster,Consumer,United States,San Antonio,...,78207,Central,OFF-BI-10004995,Office Supplies,Binders,GBC DocuBind P400 Electric Binding System,2177.584,8,0.8,-3701.8928
683,684,US-2017-168116,11/4/2017,11/4/2017,Same Day,GT-14635,Grant Thornton,Corporate,United States,Burlington,...,27217,South,TEC-MA-10004125,Technology,Machines,Cubify CubeX 3D Printer Triple Head Print,7999.980,4,0.5,-3839.9904
7772,7773,CA-2016-108196,11/25/2016,12/2/2016,Standard Class,CS-12505,Cindy Stewart,Consumer,United States,Lancaster,...,43130,East,TEC-MA-10000418,Technology,Machines,Cubify CubeX 3D Printer Double Head Print,4499.985,5,0.7,-6599.9780

In [25]:
# Display final filtered data

filter_sales

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2623,2624,CA-2017-127180,10/22/2017,10/24/2017,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,10024,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888
2697,2698,CA-2014-145317,3/18/2014,3/23/2014,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,32216,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784
4190,4191,CA-2017-166709,11/17/2017,11/22/2017,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856
6826,6827,CA-2016-118689,10/2/2016,10/9/2016,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760
8153,8154,CA-2017-140151,3/23/2017,3/25/2017,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808

In [26]:
west_sales

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2505,2506,CA-2014-143917,7/25/2014,7/27/2014,Second Class,KL-16645,Ken Lonsdale,Consumer,United States,San Francisco,...,94122,West,OFF-SU-10000151,Office Supplies,Supplies,High Speed Automatic Electric Letter Opener,8187.65,5,0.0,327.5060
8153,8154,CA-2017-140151,3/23/2017,3/25/2017,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.96,4,0.0,6719.9808
8858,8859,CA-2017-135909,10/13/2017,10/20/2017,Standard Class,JW-15220,Jane Waco,Corporate,United States,Sacramento,...,95823,West,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,5083.96,5,0.2,1906.4850